/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class Loginicon {
  Loginicon._();

  static const _kFontFam = 'Loginicon';

  static const IconData home_outline = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData account_circle = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData account_box = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData assignment_turned_in = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData border_color = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData content_paste = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData camera_front = const IconData(0xe806, fontFamily: _kFontFam);

}
