/// Flutter icons ToureIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ToureIcons
///      fonts:
///       - asset: fonts/ToureIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ToureIcons {
  ToureIcons._();

  static const _kFontFam = 'ToureIcons';

  static const IconData azadi = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData around = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData tent = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData crown_of_royal_design = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData first_day = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData stopwatch = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData control = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData share = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData passport_1 = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData airport = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData business_and_finance = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData passport = const IconData(0xe80b, fontFamily: _kFontFam);
}
